const initialTasks = [
  {id:1,title:'3분기 캠페인 기획안 마무리',project:'마케팅',due:'오늘',status:'progress',priority:'high',note:'목표 지표와 채널별 예산 확인'},
  {id:2,title:'신규 랜딩페이지 문구 검토',project:'웹사이트',due:'오늘',status:'todo',priority:'medium',note:'모바일 첫 화면 중심으로 검토'},
  {id:3,title:'주간 성과 데이터 정리',project:'데이터',due:'8월 12일',status:'todo',priority:'low',note:'지난주 대비 증감률 포함'},
  {id:4,title:'파트너 미팅 후속 메일 발송',project:'파트너십',due:'완료',status:'done',priority:'medium',note:'회의록과 다음 일정 공유'}
];
const priorityLabel={high:'긴급',medium:'보통',low:'여유'};
const today=()=>new Date().toLocaleDateString('sv-SE');
let tasks=load();let filter='all';let query='';let selectedDate='';
const $=s=>document.querySelector(s);
function load(){try{const saved=JSON.parse(localStorage.getItem('wonpro-todo-tasks'))||initialTasks;return saved.map(t=>({...t,createdDate:t.createdDate||today(),dueDate:t.dueDate||'',completedDate:t.completedDate||(t.status==='done'?today():'')}))}catch{return initialTasks.map(t=>({...t,createdDate:today(),dueDate:'',completedDate:t.status==='done'?today():''}))}}
function save(){localStorage.setItem('wonpro-todo-tasks',JSON.stringify(tasks))}
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
function dateTasks(){return selectedDate?tasks.filter(t=>t.createdDate===selectedDate||t.dueDate===selectedDate||t.completedDate===selectedDate):tasks}
function counts(list=dateTasks()){return{all:list.length,todo:list.filter(t=>t.status==='todo').length,progress:list.filter(t=>t.status==='progress').length,done:list.filter(t=>t.status==='done').length}}
function formatDate(value){if(!value)return'마감일 없음';return new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric'}).format(new Date(`${value}T00:00:00`))}
function dateBadges(t){if(!selectedDate)return'';return[['createdDate','등록'],['dueDate','마감'],['completedDate','완료']].filter(([key])=>t[key]===selectedDate).map(([,label])=>`<span class="date-badge">${label}</span>`).join('')}
function render(){const scoped=dateTasks(),c=counts(scoped),percent=c.all?Math.round(c.done/c.all*100):0;$('#progressText').textContent=`${percent}%`;$('#progressDetail').textContent=`${c.done}개 완료 · ${c.all-c.done}개 남음`;$('#ringText').innerHTML=`${percent}<small>%</small>`;$('#ring').style.setProperty('--p',`${percent*3.6}deg`);$('#todoCount').textContent=c.todo;$('#doingCount').textContent=c.progress;$('#doneCount').textContent=c.done;[...$('#filters').children].forEach((b,i)=>{b.querySelector('span').textContent=[c.all,c.todo,c.progress,c.done][i]});if(selectedDate){$('#boardTitle').textContent=formatDate(selectedDate)+'의 기록';$('#boardDescription').textContent='이날 등록·마감·완료한 업무를 모아봤어요.';$('#clearDate').classList.remove('hidden')}else{$('#boardTitle').textContent='나의 업무';$('#boardDescription').textContent='해야 할 일을 차근차근 정리해 보세요.';$('#clearDate').classList.add('hidden')}const visible=scoped.filter(t=>(filter==='all'||t.status===filter)&&`${t.title} ${t.project}`.toLowerCase().includes(query.toLowerCase()));$('#tasks').innerHTML=visible.length?visible.map(t=>`<article class="task ${t.status==='done'?'done':''}" data-id="${t.id}" tabindex="0" aria-label="${escapeHtml(t.title)} 상세 보기"><button class="check" aria-label="완료 처리">${t.status==='done'?'✓':''}</button><div class="task-main"><div class="title-row"><h3>${escapeHtml(t.title)}</h3><span class="priority ${t.priority}">${priorityLabel[t.priority]}</span>${dateBadges(t)}</div><p>${escapeHtml(t.note||'메모가 없습니다.')}</p><div class="meta"><span>▣ ${escapeHtml(t.project)}</span><span>◷ ${formatDate(t.dueDate)}</span><span>등록 ${formatDate(t.createdDate)}</span>${t.completedDate?`<span>완료 ${formatDate(t.completedDate)}</span>`:''}</div></div><select class="status ${t.status}" aria-label="업무 상태"><option value="todo" ${t.status==='todo'?'selected':''}>할 일</option><option value="progress" ${t.status==='progress'?'selected':''}>진행 중</option><option value="done" ${t.status==='done'?'selected':''}>완료</option></select><button class="remove" aria-label="업무 삭제">×</button></article>`).join(''):'<div class="empty"><b>✓</b><h3>이 날짜의 업무 기록이 없어요</h3><p>다른 날짜를 선택하거나 새 업무를 추가해 보세요.</p></div>';save()}
function openModal(id){$(`#${id}`).classList.remove('hidden');if(id==='reportModal')$('#reportText').value=makeReport()}
function closeModal(id){$(`#${id}`).classList.add('hidden')}
function notify(msg){const t=$('#toast');t.textContent=`✓ ${msg}`;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)}
function setTaskStatus(id,status){tasks=tasks.map(t=>t.id===id?{...t,status,completedDate:status==='done'?(t.completedDate||today()):''}:t)}
function openTask(id){const task=tasks.find(t=>t.id===id);if(!task)return;const form=$('#editForm');form.elements.id.value=task.id;form.elements.title.value=task.title;form.elements.project.value=task.project;form.elements.dueDate.value=task.dueDate||'';form.elements.note.value=task.note||'';form.elements.priority.value=task.priority;form.elements.status.value=task.status;$('#recordDates').innerHTML=`<span>등록일 <strong>${formatDate(task.createdDate)}</strong></span><span>완료일 <strong>${task.completedDate?formatDate(task.completedDate):'미완료'}</strong></span>`;openModal('detailModal')}
function makeReport(){const target=selectedDate||today(),scoped=selectedDate?dateTasks():tasks;const list=s=>{const a=scoped.filter(t=>t.status===s);return a.length?a.map(t=>`• ${t.title} (${t.project})`).join('\n'):'• 해당 없음'};const c=counts(scoped),p=c.all?Math.round(c.done/c.all*100):0;return `[업무보고] ${new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date(`${target}T00:00:00`))}\n\n1. 완료 업무\n${list('done')}\n\n2. 진행 중 업무\n${list('progress')}\n\n3. 예정 업무\n${list('todo')}\n\n4. 진행률\n전체 ${c.all}건 중 ${c.done}건 완료 (${p}%)`}
$('#addButton').onclick=()=>openModal('addModal');$('#reportButton').onclick=$('#navReport').onclick=()=>openModal('reportModal');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
$('#search').oninput=e=>{query=e.target.value;render()};$('#filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;filter=b.dataset.filter;[...$('#filters').children].forEach(x=>x.classList.toggle('selected',x===b));render()};
$('#historyDate').onchange=e=>{selectedDate=e.target.value;render()};$('#todayButton').onclick=()=>{selectedDate=today();$('#historyDate').value=selectedDate;render()};$('#clearDate').onclick=()=>{selectedDate='';$('#historyDate').value='';render()};
$('#tasks').onclick=e=>{const card=e.target.closest('.task');if(!card)return;const id=Number(card.dataset.id);if(e.target.closest('.check')){const task=tasks.find(t=>t.id===id);setTaskStatus(id,task.status==='done'?'todo':'done');render();return}if(e.target.closest('.remove')){tasks=tasks.filter(t=>t.id!==id);render();return}if(e.target.closest('.status'))return;openTask(id)};
$('#tasks').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.task')){e.preventDefault();openTask(Number(e.target.dataset.id))}};
$('#tasks').onchange=e=>{if(!e.target.matches('.status'))return;const card=e.target.closest('.task');setTaskStatus(Number(card.dataset.id),e.target.value);render()};
$('#taskForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);tasks.unshift({id:Date.now(),title:f.get('title'),project:f.get('project')||'일반',dueDate:f.get('dueDate')||'',note:f.get('note')||'',priority:f.get('priority'),status:'todo',createdDate:today(),completedDate:''});e.target.reset();closeModal('addModal');notify('새 업무를 추가했어요');render()};
$('#editForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=Number(f.get('id')),status=f.get('status');tasks=tasks.map(t=>t.id===id?{...t,title:f.get('title'),project:f.get('project')||'일반',dueDate:f.get('dueDate')||'',note:f.get('note')||'',priority:f.get('priority'),status,completedDate:status==='done'?(t.completedDate||today()):''}:t);closeModal('detailModal');notify('업무 내용을 수정했어요');render()};
$('#copyReport').onclick=async()=>{await navigator.clipboard.writeText($('#reportText').value);notify('보고서를 복사했어요')};
render();
